
"""
    split_mean(data::Matrix{Float32}, n::Int)
Splits the data into `n` equal parts along the second dimension and computes the mean of each part.
- `data`: A matrix of shape (neurons, time) containing the activity of each neuron across time.
- `n`: The number of parts to split the data into.
Returns a matrix of shape (neurons, n) containing the mean activity of each neuron for each part.
"""
function split_mean(data, n)
    n_parts = size(data, 2) ÷ n
    means = zeros(Float32, size(data, 1), n)
    for i = 1:n
        start_idx = (i - 1) * n_parts + 1
        end_idx = i * n_parts
        means[:, i] = mean(data[:, start_idx:end_idx], dims = 2)[:, 1]
    end
    return means
end

"""
    generate_synthetic_data(num_classes::Int, num_neurons::Int,  num_trials::Int; num_signals::Int = 10, noise_level= 1.0, baseline_bias = 0.0)
Generates synthetic neural activity data for a given number of classes, neurons, and trials. The data is generated by creating a set of signals for each class and adding noise to create variability across trials.
- `num_classes`: The number of distinct classes or conditions for which to generate data.
- `num_neurons`: The number of neurons to simulate.
- `num_trials`: The number of trials to simulate for each class.
- `num_signals`: The number of distinct signals to generate (default is 10).
- `noise_level`: The standard deviation of the noise to add to the signals (default is 1.0).
- `baseline_bias`: A bias added to the signal to create a baseline activity (default is 0.0).
Returns a 3D array of shape (num_classes, num_neurons, num_trials) containing the simulated neural activity for each class, neuron, and trial.
"""
function generate_synthetic_data(num_classes::Int, num_neurons::Int,  num_trials::Int; num_signals::Int = 10, noise_level= 1.0, baseline_bias = 0.0)
    signal = [randn(num_neurons).+collect(range(0,baseline_bias,num_neurons)) for _ in 1:num_signals]
    dd = zeros(Float32, num_neurons)
    activities = zeros(Float32, num_classes,num_neurons, num_trials)
    for i in 1:num_classes
        if num_signals > 0
            gr_size = num_classes ÷ num_signals
            dd = signal[((i-1) ÷ gr_size)+1]
        end
        for j in 1:num_trials
            activities[i, :, j] = dd + noise_level*randn(num_neurons)
        end
    end
    return activities
end


"""
    noise_correction(activities::Array{Float32, 3})

Corrects the correlation between neurons by accounting for noise correlations.
- `activities`: A 3D array of shape (neurons, time, trials) containing the activity of each neuron across time and trials.
Returns a matrix of noise-corrected correlations between neurons.
"""
function noise_correction(activities::Array{Float32, 3}; n_group=5)
    all_corr = zeros(Float32, size(activities, 1), size(activities, 1))
    for i in axes(activities, 1)
        for j = axes(activities, 1)
            activity_i = activities[i, :, :] |> x-> split_mean(x, n_group)
            activity_j = activities[j, :, :] |> x-> split_mean(x, n_group)

            R = size(activity_i, 2)
            ρ0 = sum(cor(activity_j, activity_i))/R^2
            ns_cor_i = cor(activity_i) |> x->(sum(x)-size(x, 1)) / (R*(R-1))
            ns_cor_j = cor(activity_j) |> x->(sum(x)-size(x, 1)) / (R*(R-1))
            correction = sqrt(abs(ns_cor_i * ns_cor_j))
            ρ = ρ0 / correction
            all_corr[i, j] = ρ
            if correction < 0.05 # (or some threshold based on the expected noise correlation)
                # (ns_cor_i<0.001 || ns_cor_j < 0.001)
                all_corr[i, j] = 0
            end
            # end
            j == i && (all_corr[i, j] = 1.0)
            all_corr[j, i] = all_corr[i, j]
        end
    end
    all_corr 
end

export split_mean, generate_synthetic_data, noise_correction